# Generated by Django 4.0.5 on 2022-06-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Product Name')),
                ('price', models.FloatField(default=0.0, verbose_name='Product Price')),
                ('stock', models.IntegerField(default=0, verbose_name='Product Stock')),
                ('promotion', models.CharField(max_length=180, verbose_name='Product Promotion')),
                ('description', models.TextField(blank=True, verbose_name='Product description')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='products', verbose_name='Prodact image')),
                ('options', models.CharField(max_length=120, verbose_name='Product options')),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
