# Generated by Django 4.0.5 on 2022-06-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_products_delete_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(blank=True, verbose_name='Product_description'),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Product_Name'),
        ),
        migrations.AlterField(
            model_name='products',
            name='options',
            field=models.CharField(max_length=120, verbose_name='Product_options'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.FloatField(default=0.0, verbose_name='Product_Price'),
        ),
        migrations.AlterField(
            model_name='products',
            name='promotion',
            field=models.CharField(max_length=180, verbose_name='Product_Promotion'),
        ),
        migrations.AlterField(
            model_name='products',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Product_Stock'),
        ),
        migrations.AlterField(
            model_name='products',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='products', verbose_name='Prodact_image'),
        ),
    ]
