# Generated by Django 4.0.5 on 2022-06-24 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='Product_TAGS',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.products'),
        ),
    ]
