# Generated by Django 4.0.5 on 2022-06-24 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_alter_tags_product_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tags',
            old_name='Product_TAGS',
            new_name='Product',
        ),
    ]
