# Generated by Django 4.0.5 on 2022-06-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Client'),
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=128, max_length=128, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('Products', models.ManyToManyField(to='ecommerce.products')),
            ],
        ),
    ]
