# Generated by Django 4.0.5 on 2022-06-24 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_alter_client_name_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('quant', models.IntegerField(default=0, verbose_name='quantite')),
                ('etat', models.CharField(max_length=120, verbose_name='etat')),
                ('Client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.client')),
                ('Product', models.ManyToManyField(to='ecommerce.products')),
            ],
        ),
    ]
